//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkWorks01
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABLESCORE
    {
        public int SCOREID { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> LessonId { get; set; }
        public Nullable<short> Exam1 { get; set; }
        public Nullable<short> Exam2 { get; set; }
        public Nullable<short> Exam3 { get; set; }
        public Nullable<decimal> Average { get; set; }
        public Nullable<bool> Situation { get; set; }
    
        public virtual TABLELESSON TABLELESSON { get; set; }
        public virtual TABLESTUDENT TABLESTUDENT { get; set; }
    }
}
